<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class NacionalidadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Lista de nacionalidades que vamos a insertar
        $nacionalidades = [
        'Afgana',
        'Albana',
        'Alemana',
        'Andorrana',
        'Angoleña',
        'Antiguana y Barbadense',
        'Argentina',
        'Armenia',
        'Arubeña',
        'Australiana',
        'Austríaca',
        'Azerbaiyana',
        'Bahameña',
        'Bahreiní',
        'Bangladesí',
        'Barbadense',
        'Belga',
        'Beliceña',
        'Beninesa',
        'Bermudeña',
        'Bielorrusa',
        'Birmana',
        'Boliviana',
        'Bosnia',
        'Botswanesa',
        'Brasileña',
        'Británica',
        'Bruneana',
        'Búlgara',
        'Burkinesa',
        'Burundesa',
        'Butanesa',
        'Cabo Verdiana',
        'Camboyana',
        'Camerunesa',
        'Canadiense',
        'Centroafricana',
        'Checa',
        'Chilena',
        'China',
        'Chipriota',
        'Colombiana',
        'Comorense',
        'Congoleña',
        'Congoleña (Rep. Democrática)',
        'Coreana del Norte',
        'Coreana del Sur',
        'Costarricense',
        'Croata',
        'Cubana',
        'Danesa',
        'Dominicana',
        'Ecuatoriana',
        'Egipcia',
        'Emiratí',
        'Eritrea',
        'Eslovaca',
        'Eslovena',
        'Española',
        'Estadounidense',
        'Estonia',
        'Etíope',
        'Fiyiana',
        'Filipina',
        'Finlandesa',
        'Francesa',
        'Gabonense',
        'Galesa',
        'Gambiana',
        'Georgiana',
        'Ghanesa',
        'Griega',
        'Guatemalteca',
        'Guineana',
        'Guineana-Bisáu',
        'Guyanesa',
        'Haitiana',
        'Hondureña',
        'Húngara',
        'India',
        'Indonesia',
        'Iraní',
        'Iraquí',
        'Irlandesa',
        'Islandesa',
        'Israelí',
        'Italiana',
        'Jamaicana',
        'Japonesa',
        'Jordana',
        'Kazaja',
        'Keniata',
        'Kirguisa',
        'Kiribatiana',
        'Kosovar',
        'Kuwaití',
        'Laosiana',
        'Letona',
        'Libanesa',
        'Liberiana',
        'Libia',
        'Liechtensteiniana',
        'Lituana',
        'Luxemburguesa',
        'Macedonia',
        'Malasia',
        'Malauí',
        'Maldiva',
        'Malgache',
        'Maliense',
        'Maltesa',
        'Marfileña',
        'Marroquí',
        'Marshallesa',
        'Mauriciana',
        'Mauritana',
        'Mexicana',
        'Micronesia',
        'Moldava',
        'Monegasca',
        'Mongola',
        'Montenegrina',
        'Mozambiqueña',
        'Namibia',
        'Nauruana',
        'Nepalí',
        'Nicaragüense',
        'Nigeriana',
        'Nigerina',
        'Norcoreana',
        'Noruega',
        'Neozelandesa',
        'Omán',
        'Paquistaní',
        'Palauana',
        'Palestina',
        'Panameña',
        'Papú',
        'Paraguaya',
        'Peruana',
        'Polaca',
        'Portuguesa',
        'Qatarí',
        'Reino Unido',
        'Rumana',
        'Rusa',
        'Ruandesa',
        'Salvadoreña',
        'Samoana',
        'Sanvicentina',
        'Santa Lucía',
        'Santotomense',
        'Saudí',
        'Senegalesa',
        'Serbia',
        'Seychellense',
        'Sierra Leonesa',
        'Singapurense',
        'Siria',
        'Somalí',
        'Sri Lanka',
        'Sudafricana',
        'Sudanesa',
        'Sueca',
        'Suiza',
        'Surinamesa',
        'Suazi',
        'Tailandesa',
        'Tanzana',
        'Tayika',
        'Timorense',
        'Togolesa',
        'Tongana',
        'Trinitense',
        'Tunecina',
        'Turca',
        'Turkmena',
        'Tuvaluana',
        'Ucraniana',
        'Ugandesa',
        'Uruguaya',
        'Uzbeca',
        'Vanuatense',
        'Vaticana',
        'Venezolana',
        'Vietnamita',
        'Yemení',
        'Zambiana',
        'Zimbabuense'
                    ];

        // Insertar cada nacionalidad en la tabla, una por una
        foreach ($nacionalidades as $nombre) {
            DB::table('nacionalidades')->insert([
                'nacionalidad' => $nombre,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'created_by' => 1, // ID del usuario que creó esto, puedes cambiarlo dinámicamente si lo necesitas
                'updated_by' => 1,
            ]);
        }
    }
}
