import {
    Activity,
    ArrowRight,
    BarChart3,
    Building2,
    CalendarDays,
    Check,
    CheckCircle2,
    ClipboardList,
    Clock3,
    CreditCard,
    createIcons,
    FileText,
    HeartPulse,
    LoaderCircle,
    Lock,
    LogIn,
    Mail,
    MapPin,
    MessageSquare,
    Phone,
    ShieldCheck,
    Sparkles,
    Users,
    XCircle,
} from 'lucide';

document.addEventListener('DOMContentLoaded', () => {
    createIcons({
        icons: {
            Activity,
            ArrowRight,
            BarChart3,
            Building2,
            CalendarDays,
            Check,
            CheckCircle2,
            ClipboardList,
            Clock3,
            CreditCard,
            FileText,
            HeartPulse,
            LoaderCircle,
            Lock,
            LogIn,
            Mail,
            MapPin,
            MessageSquare,
            Phone,
            ShieldCheck,
            Sparkles,
            Users,
            XCircle,
        },
    });
});
